name: AlphaElytraRemover
version: 2.5
author: AlphaBlock4k
description: "Dieses Plugin entfernt Elytras aus Itemframes in den Endwelten."
website: https://guns.lol/AlphaBlock4k
main: com.alphablock.AlphaElytraRemover
api-version: 1.21.1
commands:
  aereload:
    description: Lädt die Konfiguration des AlphaElytraRemover-Plugins neu.
    usage: /aereload
    permission: ae.use.aereload

permissions:
  ae.use.aereload:
    default: op
